Repository checkout/frames-ios, pull requests merged in 2022-07, with the labels that each got.

#189 Add Secure View for Input View
  Source/UI/NewUI/CommonUI/View/Core/SecureDisplayView.swift
  Source/UI/NewUI/CommonUI/View/Core/TextFieldView.swift
  Source/UI/NewUI/PaymentForm/ViewController/PaymentViewController.swift
  Tests/UI/New UI/BillingForm/View/ExpiryDateViewTests.swift
  Tests/UI/New UI/BillingForm/View/MirrorObject.swift
  Tests/UI/New UI/BillingForm/View/SecureDisplayViewTests.swift
  Tests/UI/New UI/BillingForm/View/TextFieldViewTests.swift
  iOS Example Frame Carthage/iOS Example Frame Carthage.xcodeproj/project.pbxproj
Labels: Ready for review

#188 Add Expiry Date business logic
  Checkout/Checkout/Integration/CardValidatorTests.swift
  Checkout/Checkout/Source/Model/ExpiryDate.swift
  Checkout/Checkout/Source/Protocols/CalendarProtocol.swift
  Checkout/Checkout/Test/Stubs/StubCalendar.swift
  Source/UI/NewUI/BillingForm/Default Implementation/Elements/TextField/DefaultTextField.swift
  Source/UI/NewUI/BillingForm/View/BillingFormCellTextField.swift
  Source/UI/NewUI/CommonUI/Protocols/Elements/ElementTextFieldStyle.swift
  Source/UI/NewUI/CommonUI/View/Component/InputView.swift
  Source/UI/NewUI/CommonUI/View/Core/ButtonView.swift
  Source/UI/NewUI/CommonUI/View/Core/SecureDisplayView.swift
  Source/UI/NewUI/CommonUI/View/Core/TextFieldView.swift
  Source/UI/NewUI/PaymentForm/Default Implementation/ExpiryDate/DefaultExpiryDateFormStyle.swift
  Source/UI/NewUI/PaymentForm/Factory/PaymentFormFactory.swift
  Source/UI/NewUI/PaymentForm/View/ExpiryDateView.swift
  Source/UI/NewUI/PaymentForm/ViewController/PaymentViewController.swift
  Source/UI/NewUI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift
  Source/UI/NewUI/PaymentForm/ViewModel/PaymentViewModel.swift
  Tests/UI/New UI/BillingForm/View/ExpiryDateViewTests.swift
  Tests/UI/New UI/BillingForm/View/MirrorObject.swift
  Tests/UI/New UI/BillingForm/View/SecureDisplayViewTests.swift
  Tests/UI/New UI/BillingForm/View/TextFieldViewTests.swift
  Tests/UI/New UI/BillingForm/ViewModel/PaymentViewModelTests.swift
  iOS Example Frame Carthage/iOS Example Frame Carthage.xcodeproj/project.pbxproj
  iOS Example Frame Carthage/iOS Example FrameUITests/iOS_Example_FrameUITests.swift
Labels: Ready for review

#194 BugFix: Fixed issues from show and tell meeting
  Source/UI/NewUI/CommonUI/View/TableViewCell/SelectionButtonTableViewCell.swift
  Source/UI/NewUI/PaymentForm/View/BillingSummary/BillingFormSummaryView.swift
  Source/UI/NewUI/PaymentForm/View/ExpiryDateView.swift
  Source/UI/NewUI/PaymentForm/ViewController/PaymentViewController.swift
  Source/UI/NewUI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift
  iOS Example Frame/iOS Example Frame/MainViewController.swift
Labels: Ready for review

#191 Feature/PIMOB-1274: Expiry date validation logic
  Source/Resources/en.lproj/Localizable.strings
  Source/UI/NewUI/PaymentForm/View/ExpiryDateView.swift
  Tests/UI/New UI/BillingForm/View/ExpiryDateViewTests.swift
Labels: Dont merge, Ready for review

#192 Feature/PIMOB-1274: Expiry date error messages
  Source/Core/Constants+LocalizationKeys.swift
  Source/Core/Constants+Style.swift
  Source/Resources/en.lproj/Localizable.strings
  Source/UI/NewUI/BillingForm/View/BillingFormCellTextField.swift
  Source/UI/NewUI/CommonUI/View/Component/InputView.swift
  Source/UI/NewUI/CommonUI/View/Core/TextFieldView.swift
  Source/UI/NewUI/PaymentForm/Default Implementation/ExpiryDate/DefaultExpiryDateFormStyle.swift
  Source/UI/NewUI/PaymentForm/View/ExpiryDateView.swift
  Tests/UI/New UI/BillingForm/View/ExpiryDateViewTests.swift
Labels: Dont merge, Ready for review

#193 PIMOB-1281: Fix chevron color
  Source/UI/NewUI/CommonUI/View/Core/ImageContainerView.swift
  Source/UI/NewUI/CommonUI/View/TableViewCell/SelectionButtonTableViewCell.swift
  Source/UI/NewUI/PaymentForm/View/BillingSummary/BillingFormSummaryView.swift
  Source/UI/NewUI/PaymentForm/View/ExpiryDateView.swift
  Source/UI/NewUI/PaymentForm/ViewController/PaymentViewController.swift
  Source/UI/NewUI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift
  iOS Example Frame/iOS Example Frame/CustomStyle1.swift
  iOS Example Frame/iOS Example Frame/CustomStyle2.swift
  iOS Example Frame/iOS Example Frame/MainViewController.swift
Labels: Ready for review

#203 Add CardValidator to payment view model
  Source/UI/NewUI/PaymentForm/Factory/PaymentFormFactory.swift
  Source/UI/NewUI/PaymentForm/View/ExpiryDateView.swift
  Source/UI/NewUI/PaymentForm/ViewController/PaymentViewController.swift
  Source/UI/NewUI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift
  Source/UI/NewUI/PaymentForm/ViewModel/PaymentViewModel.swift
  Tests/UI/New UI/BillingForm/View/ExpiryDateViewTests.swift
  Tests/UI/New UI/BillingForm/ViewModel/PaymentViewModelTests.swift
  Tests/UI/New UI/PaymentFormFactoryTests.swift
  iOS Example Frame Carthage/iOS Example Frame Carthage.xcodeproj/project.pbxproj
  iOS Example Frame/iOS Example Frame/MainViewController.swift
Labels: Ready for review

#204 `shouldImageFlippedForRightToLeftLayoutDirection` is provided by the merchant
  Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Header/Cancel/DefaultCancelButtonFormStyle.swift
  Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Header/Done/DefaultDoneFormButtonStyle.swift
  Source/UI/NewUI/BillingForm/Default Implementation/Elements/Country/Country.swift
  Source/UI/NewUI/CommonUI/Protocols/Elements/ElementButtonStyle.swift
  Source/UI/NewUI/CommonUI/View/Component/SelectionButtonView.swift
  Source/UI/NewUI/PaymentForm/Default Implementation/BillingFormSummary/Summary/Button/DefaultAddBillingDetailsButtonStyle.swift
  Source/UI/NewUI/PaymentForm/Default Implementation/BillingFormSummary/Summary/Button/DefaultEditBillingDetailsButtonStyle.swift
  Source/UI/NewUI/PaymentForm/Factory/PaymentFormFactory.swift
  Source/UI/NewUI/PaymentForm/View/BillingFormSummaryView.swift
  Tests/UI/New UI/PaymentFormFactoryTests.swift
  iOS Example Frame/iOS Example Frame/CustomStyle1.swift
  iOS Example Frame/iOS Example Frame/CustomStyle2.swift
  iOS Example Frame/iOS Example Frame/MainViewController.swift
Labels: Ready for review

#220 PIMBO-1337: Update some localisations
  Source/Core/Constants/Constants+LocalizationKeys.swift
  Source/Core/Constants/Constants+Style.swift
  Source/Resources/en.lproj/Localizable.strings
  Source/UI/NewUI/PaymentForm/Default Implementation/DefaultPaymentHeaderCellStyle.swift
  Tests/UI/New UI/BillingForm/ViewModel/PaymentViewModelTests.swift
Labels: Fix

#221 PIMOB-1337: County billing form field should be optional
  Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Fields/State/DefaultBillingFormStateCellStyle.swift
Labels: Fix

#218 PIMOB-1191: Invalid string case of of pre-filled expiry date text.
  Source/UI/NewUI/PaymentForm/View/ExpiryDateView.swift
  Tests/UI/New UI/BillingForm/View/ExpiryDateViewTests.swift
  iOS Example Frame/iOS Example Frame/CustomStyle1.swift
Labels: Fix

#223 Fix: The border colour should turn to the standard black colour if I …
  Source/UI/NewUI/CommonUI/View/Component/InputView.swift
Labels: Fix

#222 PIMOB:1337: Dismiss keyboard on touch on white spaces view for all screens
  Source/Extensions/UIViewExtensions.swift
  Source/UI/NewUI/BillingForm/View/BillingFormCellTextField.swift
  Source/UI/NewUI/BillingForm/ViewController/BillingFormViewController.swift
  Source/UI/NewUI/CommonUI/View/Component/InputView.swift
Labels: Fix

#224 PIMOB-1278: Add Payment Form Presented analytics event
  Source/Core/CheckoutAPIService.swift
  Source/Core/Logging/FramesLogEvent.swift
  Source/UI/Controllers/CardViewController.swift
  Source/UI/NewUI/PaymentForm/Factory/PaymentFormFactory.swift
  Source/UI/NewUI/PaymentForm/Model/PaymentFormConfiguration.swift
  Source/UI/NewUI/PaymentForm/Model/PaymentStyle.swift
  Source/UI/NewUI/PaymentForm/ViewController/PaymentViewController.swift
  Source/UI/NewUI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift
  Source/UI/NewUI/PaymentForm/ViewModel/PaymentViewModel.swift
  Tests/Core/Logging/FramesLogEventTests.swift
  Tests/Core/Logging/ThemeTests.swift
  Tests/Mocks/StubFramesEventLogger.swift
  Tests/Mocks/StubTheme.swift
  Tests/UI/CardViewControllerTests.swift
  Tests/UI/New UI/BillingForm/ViewController/PaymentViewControllerTests.swift
  Tests/UI/New UI/BillingForm/ViewModel/PaymentViewModelTests.swift
  Tests/UI/New UI/PaymentFormFactoryTests.swift
  iOS Example Frame Carthage/iOS Example Frame Carthage.xcodeproj/project.pbxproj
  iOS Example Frame/iOS Example Frame/MainViewController.swift
Labels: Feature

#226 PIMOB-1279: Trigger analytics event on billing VC willAppear
  Source/UI/NewUI/BillingForm/ViewController/BillingFormViewController.swift
  Source/UI/NewUI/BillingForm/ViewModel/BillingFormViewModel.swift
  Source/UI/NewUI/BillingForm/ViewModel/DefaultBillingFormViewModel.swift
  Source/UI/NewUI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift
  Tests/Mocks/BillingFormViewModelMockDelegate.swift
  Tests/UI/New UI/BillingForm/ViewController/BillingFormViewControllerTests.swift
  Tests/UI/New UI/BillingForm/ViewModel/BillingFormViewModelTests.swift
  Tests/UI/New UI/BillingForm/ViewModel/PaymentViewModelTests.swift
Labels: Feature

#228 PIMOB-987: Add event for start of payment journey
  Source/Core/CheckoutAPIService.swift
  Source/Core/Logging/FramesLogEvent.swift
  Source/UI/NewUI/BillingForm/ViewModel/DefaultBillingFormViewModel.swift
  Source/UI/NewUI/PaymentForm/Factory/PaymentFormFactory.swift
  Source/UI/NewUI/PaymentForm/Model/PaymentFormConfiguration.swift
  Source/UI/NewUI/PaymentForm/Model/PaymentStyle.swift
  Source/UI/NewUI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift
  iOS Example Frame/iOS Example Frame/MainViewController.swift
Labels: Feature
