Repository checkout/frames-ios, pull requests merged in 2022-09, with the labels that each got.

#259 PIMOB-1396: Fix Done states validation in the Billing Form
  Source/UI/BillingForm/ViewModel/DefaultBillingFormViewModel.swift
Labels: Fix

#266 PIMOB-1415: Update Discover card scheme regex
  Checkout/Checkout/Source/Model/Card+Scheme.swift
  Checkout/Checkout/Test/Validation/CardNumberValidatorTests.swift
Labels: Enhancement

#262 PIMOB-1375: Fix iPad scroll view background
  Source/UI/PaymentForm/ViewController/PaymentViewController.swift
  iOS Example Frame/iOS Example Frame/Factory/Factory.swift
Labels: Fix

#264 PIMOB-1379: Improve cardholder input view behaviour
  Source/UI/CommonUI/View/Component/InputView.swift
  Source/UI/PaymentForm/View/CardholderName/CardholderView.swift
  Source/UI/PaymentForm/View/CardholderName/CardholderViewModel.swift
  Source/UI/PaymentForm/ViewController/PaymentViewController.swift
  Source/UI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift
  Source/UI/PaymentForm/ViewModel/PaymentViewModel.swift
  Tests/UI/BillingForm/ViewModel/PaymentViewModelTests.swift
  Tests/UI/PaymentForm/CardholderViewModelTests.swift
  iOS Example Frame/iOS Example Frame/Factory/Factory.swift
Labels: Fix

#269 PIMOB-1413: Validate CVV input for Payment button state update
  Source/UI/PaymentForm/View/SecurityCodeView.swift
  Source/UI/PaymentForm/ViewController/PaymentViewController.swift
  Source/UI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift
  Tests/Mocks/PaymentViewControllerMockDelegate.swift
  Tests/UI/BillingForm/ViewModel/PaymentViewModelTests.swift
  Tests/UI/PaymentForm/PaymentViewControllerTests.swift
Labels: Fix

#268 PIMOB-1416: Add UI Test for full UI journey
  Source/UI/BillingForm/View/BillingFormHeaderCell.swift
  Source/UI/BillingForm/ViewModel/DefaultBillingFormViewModel.swift
  Source/UI/PaymentForm/View/BillingFormSummaryView.swift
  Source/UI/Theme/Generic/Theme+Button.swift
  bitrise.yml
  iOS Example Frame/iOS Example Frame/Factory/Factory+UITest.swift
  iOS Example Frame/iOS Example Frame/Factory/Factory.swift
  iOS Example Frame/iOS Example FrameUITests/FrameUITests.swift
  iOS Example Frame/iOS Example FrameUITests/XCUIApplication+Extension.swift
Labels: Enhancement

#274 PIMOB-1361: Support Arabic RTL language
  Source/Core/Constants/Constants+LocalizationKeys.swift
  Source/Resources/ar.lproj/Localizable.strings
  Source/Resources/en.lproj/Localizable.strings
  Source/UI/BillingForm/Default Implementation/Elements/Country/DefaultCountryFormButtonStyle.swift
  Source/UI/CountrySelection/CountrySelectionViewController.swift
  Source/UI/PaymentForm/Default Implementation/BillingFormSummary/Summary/Button/DefaultAddBillingDetailsButtonStyle.swift
  Source/UI/PaymentForm/Default Implementation/BillingFormSummary/Summary/Button/DefaultEditBillingDetailsButtonStyle.swift
  Source/UI/PaymentForm/Default Implementation/BillingFormSummary/Summary/View/DefaultAddBillingDetailsViewStyle.swift
  Source/UI/PaymentForm/Default Implementation/BillingFormSummary/Summary/View/DefaultBillingSummaryViewStyle.swift
  Source/UI/PaymentForm/View/CardholderName/CardholderViewModel.swift
  Source/UI/PaymentForm/ViewController/PaymentViewController.swift
  Tests/Resources/ResourcesTests.swift
  iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.pbxproj
  iOS Example Frame/iOS Example Frame/Storyboards/Base.lproj/Main.storyboard
  iOS Example Frame/iOS Example Frame/Storyboards/ar-001.lproj/LaunchScreen.strings
  iOS Example Frame/iOS Example Frame/Storyboards/ar-001.lproj/Main.strings
Labels: Ready for review, Feature

#271 SwiftLint(1)
  .swiftlint.yml
  Source/CheckoutTheme.swift
  Source/Extensions/Dictionary+Additions.swift
  Source/Extensions/UIViewControllerExtensions.swift
  Source/UI/BillingForm/Default Implementation/BillingForm/Fields/AddressLine1/DefaultBillingFormAddressLine1CellStyle.swift
  Source/UI/BillingForm/Default Implementation/BillingForm/Fields/AddressLine2/DefaultBillingFormAddressLine2CellStyle.swift
  Source/UI/BillingForm/Default Implementation/BillingForm/Fields/City/DefaultBillingFormCityCellStyle.swift
  Source/UI/BillingForm/Default Implementation/BillingForm/Fields/Country/DefaultBillingFormCountryCellStyle.swift
  Source/UI/BillingForm/Default Implementation/BillingForm/Fields/FullName/DefaultBillingFormFullNameCellStyle.swift
  Source/UI/BillingForm/Default Implementation/BillingForm/Fields/PhoneNumber/DefaultBillingFormPhoneNumberCellStyle.swift
  Source/UI/BillingForm/Default Implementation/BillingForm/Fields/Postcode/DefaultBillingFormPostCodeCellStyle.swift
  Source/UI/BillingForm/Default Implementation/BillingForm/Fields/State/DefaultBillingFormStateCellStyle.swift
  Source/UI/BillingForm/Default Implementation/BillingForm/Header/Cancel/DefaultCancelButtonFormStyle.swift
  Source/UI/BillingForm/Default Implementation/BillingForm/Header/Done/DefaultDoneFormButtonStyle.swift
  Source/UI/BillingForm/Default Implementation/BillingForm/Header/Title/DefaultHeaderLabelFormStyle.swift
  Source/UI/BillingForm/Default Implementation/Elements/Country/DefaultCountryFormButtonStyle.swift
  Source/UI/BillingForm/Default Implementation/Elements/Error/DefaultErrorInputLabelStyle.swift
  Source/UI/BillingForm/Default Implementation/Elements/Hint/DefaultHintInputLabelStyle.swift
  Source/UI/BillingForm/Default Implementation/Elements/TextField/DefaultTextField.swift
  Source/UI/BillingForm/Default Implementation/Elements/Title/DefaultTitleLabelStyle.swift
  Source/UI/BillingForm/FramesFactory.swift
  Source/UI/BillingForm/Style Protocol/BillingFormHeaderCellStyle.swift
  Source/UI/BillingForm/View/BillingFormTextFieldView.swift
  Source/UI/BillingForm/ViewModel/DefaultBillingFormViewModel.swift
  Source/UI/CommonUI/View/Core/ButtonView.swift
  Source/UI/PaymentForm/Default Implementation/BillingFormSummary/Summary/Button/DefaultAddBillingDetailsButtonStyle.swift
  Source/UI/PaymentForm/Default Implementation/BillingFormSummary/Summary/Button/DefaultEditBillingDetailsButtonStyle.swift
  Source/UI/PaymentForm/Default Implementation/BillingFormSummary/Summary/View/DefaultAddBillingDetailsViewStyle.swift
  Source/UI/PaymentForm/Default Implementation/BillingFormSummary/Summary/View/DefaultBillingSummaryViewStyle.swift
  Source/UI/PaymentForm/Default Implementation/CardNumber/DefaultCardNumberFormStyle.swift
  Source/UI/PaymentForm/Default Implementation/Cardholder/DefaultCardholderFormStyle.swift
  Source/UI/PaymentForm/Default Implementation/DefaultPayButtonFormStyle.swift
  Source/UI/PaymentForm/Default Implementation/DefaultPaymentHeaderCellStyle.swift
  Source/UI/PaymentForm/Default Implementation/ExpiryDate/DefaultExpiryDateFormStyle.swift
  Source/UI/PaymentForm/Default Implementation/SecurityCode/DefaultSecurityCodeFormStyle.swift
  Source/UI/PaymentForm/View/SecurityCodeView.swift
  Source/UI/PaymentForm/ViewController/PaymentViewController.swift
  Source/UI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift
  Source/UI/PaymentForm/ViewModel/PaymentViewModel.swift
  Source/UI/Theme/BillingForm/Theme+BillingCountryInput.swift
  Source/UI/Theme/Generic/Theme+Button.swift
  Source/UI/Theme/Generic/Theme+Error.swift
  Source/UI/Theme/Generic/Theme+Mandatory.swift
  Source/UI/Theme/Generic/Theme+PageHeaderTitle.swift
  Source/UI/Theme/Generic/Theme+Subtitle.swift
  Source/UI/Theme/Generic/Theme+TextField.swift
  Source/UI/Theme/Generic/Theme+Title.swift
  Source/UI/Theme/PaymentForm/Theme+AddBillingSectionButton.swift
  Source/UI/Theme/PaymentForm/Theme+BillingSummary.swift
  Source/UI/Theme/PaymentForm/Theme+CardNumberSection.swift
  Source/UI/Theme/PaymentForm/Theme+PayButton.swift
  Source/UI/Theme/PaymentForm/Theme+PaymentHeader.swift
  Source/UI/Theme/PaymentForm/Theme+PaymentHeaderSubtitle.swift
  iOS Example Frame Carthage/iOS Example Frame Carthage.xcodeproj/project.pbxproj
  iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.pbxproj
  iOS Example Frame/iOS Example Frame.xcodeproj/project.pbxproj
  iOS Example Frame/iOS Example Frame/Style/CustomStyle1.swift
  iOS Example Frame/iOS Example Frame/ThemeDemo.swift
Labels: Ready for review

#272 SwiftLint(2)
  .swiftlint.yml
  Source/CardUtils.swift
  Source/Core/CheckoutAPIService.swift
  Source/Core/Constants/Constants+LocalizationKeys.swift
  Source/Core/Constants/Constants+Style.swift
  Source/Core/Constants/Constants.swift
  Source/Extensions/StringExtensions.swift
  Source/UI/3DS/ThreedsWebViewController.swift
  Source/UI/BillingForm/FramesFactory.swift
  Source/UI/BillingForm/View/BillingFormHeaderCell.swift
  Source/UI/CommonUI/View/Component/SimpleErrorView.swift
  Source/UI/PaymentForm/Factory/PaymentFormFactory.swift
  Source/UI/PaymentForm/View/ExpiryDateView.swift
  Source/UI/PaymentForm/View/SecurityCodeViewModel.swift
  Source/UI/PaymentForm/ViewController/PaymentViewController.swift
  Source/UI/Theme/PaymentForm/Theme+AddBillingSectionButton.swift
  Source/UI/Theme/PaymentForm/Theme+BillingSummary.swift
  Source/UI/Theme/PaymentForm/Theme+PaymentFormStyle.swift
  Tests/Resources/ResourcesTests.swift
  iOS Example Frame/iOS Example Frame/Factory/Factory.swift
  iOS Example Frame/iOS Example Frame/Style/CustomStyle1.swift
  iOS Example Frame/iOS Example Frame/ThemeDemo.swift
Labels: Ready for review

#273 SwiftLint(3)
  .swiftlint.yml
  Source/CardUtils.swift
  Source/CheckoutSdkIos.swift
  Source/CheckoutTheme.swift
  Source/Core/Constants/Constants+Padding.swift
  Source/Core/Constants/Constants+Style.swift
  Source/Extensions/StringExtensions.swift
  Source/Extensions/UITextFieldExtension.swift
  Source/Extensions/UIViewControllerExtensions.swift
  Source/Extensions/UIViewExtensions.swift
  Source/UI/CommonUI/View/Component/InputView.swift
  Source/UI/CountrySelection/CountrySelectionViewController.swift
  Source/UI/PaymentForm/Model/PaymentFormConfiguration.swift
  Source/UI/PaymentForm/ViewController/PaymentViewController.swift
  iOS Example Frame/iOS Example Frame/Extension/UIViewExtension.swift
  iOS Example Frame/iOS Example Frame/Factory/Factory+UITest.swift
  iOS Example Frame/iOS Example Frame/Factory/Factory.swift
  iOS Example Frame/iOS Example Frame/Resources/Fonts/UIFont+Graphik.swift
  iOS Example Frame/iOS Example Frame/Resources/Fonts/UIFont+SFMono.swift
  iOS Example Frame/iOS Example Frame/ThemeDemo.swift
  iOS Example Frame/iOS Example Frame/ViewController/HomeViewController.swift
  iOS Example Frame/iOS Example FrameUITests/FrameUITests.swift
Labels: Ready for review

#277 PIMOB-1058: Change summary billing button size
  iOS Example Frame/iOS Example Frame/Style/CustomStyle1.swift
Labels: Fix

#276 PIMOB-NONE: Isolate consumption of PhoneNumberKit components to genuine use cases
  Source/UI/BillingForm/View/BillingFormCellTextField.swift
  Source/UI/BillingForm/View/BillingFormTextFieldView.swift
  Tests/UI/BillingForm/View/BillingFormTextFieldViewTests.swift
  iOS Example Frame/iOS Example Frame/Style/CustomStyle1.swift
Labels: Fix

#282 PIMOB-1058: Fix strong reference to phoneNumberTextDelegate
  Source/UI/BillingForm/View/BillingFormPhoneNumberText.swift
Labels: Fix

#286 PIMOB-1058: Fix 3DS image Button is missing
  iOS Example Frame/iOS Example Frame/Assets.xcassets/cloud-key.imageset/Contents.json
  iOS Example Frame/iOS Example Frame/Assets.xcassets/cloud-key.imageset/cloud.png
  iOS Example Frame/iOS Example Frame/Storyboards/Base.lproj/Main.storyboard
Labels: Fix

#284 PIMOB-1058: Disable dark mode for Frames and Sample app
  Source/UI/CountrySelection/CountrySelectionViewController.swift
  iOS Example Frame/iOS Example Frame/AppDelegate.swift
Labels: Fix

#278 PIMOB-xxxx: Fix Arabic localization for carthage
  Tests/UI/BillingForm/ViewModel/PaymentViewModelTests.swift
  iOS Example Frame Carthage/iOS Example Frame Carthage.xcodeproj/project.pbxproj
  iOS Example Frame Carthage/iOS Example Frame Carthage.xcodeproj/xcshareddata/xcschemes/Frames.xcscheme
  iOS Example Frame/iOS Example Frame/Resources/ar.lproj/LaunchScreen.strings
  iOS Example Frame/iOS Example Frame/Resources/ar.lproj/Main.strings
  iOS Example Frame/iOS Example Frame/Resources/en.lproj/LaunchScreen.strings
  iOS Example Frame/iOS Example Frame/Resources/en.lproj/Main.strings
  iOS Example Frame/iOS Example Frame/Storyboards/ar.lproj/LaunchScreen.strings
  iOS Example Frame/iOS Example Frame/Storyboards/ar.lproj/Main.strings
Labels: Fix

#281 PIMob-1058: Missing border line colors for UIStackView on iOS 12
  Source/UI/CommonUI/View/Component/InputView.swift
  iOS Example Frame/iOS Example FrameUITests/FrameUITests.swift
Labels: Fix

#287 PIMOB-XXXX: Change Checkout SPM min iOS version to 12
  Checkout/Package.swift
  Checkout/SPMSample/CheckoutSPMSample.xcodeproj/project.pbxproj
Labels: Upgrade

#280 PIMOB-1058: Fix Navigation bar is always shown on iOS 12
  Source/Extensions/UIViewControllerExtensions.swift
Labels: Fix

#293 PIMOB-1427: Fix card number input should be blue when I'm filling it in
  Source/UI/CommonUI/View/Component/InputView.swift
  iOS Example Frame/iOS Example FrameUITests/FrameUITests.swift
Labels: Fix

#296 PIMOB-1441: Add Checkout UI Style by UX team
  Source/CheckoutColor.swift
  Source/UI/CommonUI/UIStyle/CKOUIStyle+UIColor.swift
  Source/UI/CommonUI/UIStyle/CKOUIStyle+UIFont.swift
  Tests/UI/CKOUIStyle/CKOUIStyleColorTests.swift
  Tests/UI/CKOUIStyle/CKOUIStyleFontTests.swift
  iOS Example Frame Carthage/iOS Example Frame Carthage.xcodeproj/project.pbxproj
  iOS Example Frame/Podfile
  iOS Example Frame/Podfile.lock
Labels: Feature

#298 PIMOB-1441: Address default theme UI comments for billing form screen
  Source/UI/BillingForm/Default Implementation/BillingForm/Fields/Country/DefaultBillingFormCountryCellStyle.swift
  Source/UI/BillingForm/Default Implementation/BillingForm/Header/Cancel/DefaultCancelButtonFormStyle.swift
  Source/UI/BillingForm/Default Implementation/BillingForm/Header/Done/DefaultDoneFormButtonStyle.swift
  Source/UI/BillingForm/ViewController/BillingFormViewController.swift
Labels: Fix

#300 PIMOB-1441: Address default theme UI comments for Sample app home screen
  iOS Example Frame/iOS Example Frame/Storyboards/Base.lproj/Main.storyboard
Labels: Fix

#299 PIMOB-1441: Address default theme UI comments for Country selection screen
  Source/Core/Constants/Constants+LocalizationKeys.swift
  Source/Resources/ar.lproj/Localizable.strings
  Source/Resources/en.lproj/Localizable.strings
  Source/UI/CountrySelection/CountrySelectionViewController.swift
Labels: Fix

#301 PIMOB-1441: Remove CKO prefix from `CKOUIStyle`
  Source/UI/BillingForm/Default Implementation/BillingForm/Header/Cancel/DefaultCancelButtonFormStyle.swift
  Source/UI/BillingForm/Default Implementation/BillingForm/Header/Done/DefaultDoneFormButtonStyle.swift
  Source/UI/BillingForm/Default Implementation/BillingForm/Header/Title/DefaultHeaderLabelFormStyle.swift
  Source/UI/BillingForm/Default Implementation/Elements/Title/DefaultTitleLabelStyle.swift
  Source/UI/CommonUI/UIStyle/FramesUIStyle+UIColor.swift
  Source/UI/CommonUI/UIStyle/FramesUIStyle+UIFont.swift
  Source/UI/CountrySelection/CountrySelectionViewController.swift
  Source/UI/PaymentForm/Default Implementation/DefaultPayButtonFormStyle.swift
  Tests/UI/CKOUIStyle/CKOUIStyleFontTests.swift
  Tests/UI/FramesUIStyle/FramesUIStyleColorTests.swift
  Tests/UI/FramesUIStyle/FramesUIStyleFontTests.swift
  iOS Example Frame Carthage/iOS Example Frame Carthage.xcodeproj/project.pbxproj
Labels: Enhancement

#302 PIMOB-1441: Apply Frames UI style
  Source/CheckoutColor.swift
  Source/CheckoutTheme.swift
  Source/Core/Constants+SchemeIcon.swift
  Source/Core/Constants/Constants+LocalizationKeys.swift
  Source/Core/Constants/Constants+Style.swift
  Source/Extensions/StringExtensions.swift
  Source/UI/BillingForm/Default Implementation/BillingForm/Fields/AddressLine2/DefaultBillingFormAddressLine2CellStyle.swift
  Source/UI/BillingForm/Default Implementation/BillingForm/Fields/State/DefaultBillingFormStateCellStyle.swift
  Source/UI/BillingForm/Default Implementation/BillingForm/Main/DefaultBillingFormStyle.swift
  Source/UI/BillingForm/Default Implementation/Elements/Country/DefaultCountryFormButtonStyle.swift
  Source/UI/BillingForm/Default Implementation/Elements/Error/DefaultErrorInputLabelStyle.swift
  Source/UI/BillingForm/Default Implementation/Elements/Hint/DefaultHintInputLabelStyle.swift
  Source/UI/BillingForm/Default Implementation/Elements/TextField/DefaultTextField.swift
  Source/UI/CommonUI/UIStyle/FramesUIStyle+UIColor.swift
  Source/UI/CommonUI/UIStyle/FramesUIStyle+UIFont.swift
  Source/UI/CountrySelection/CountrySelectionViewController.swift
  Source/UI/PaymentForm/Default Implementation/BillingFormSummary/Summary/Button/DefaultAddBillingDetailsButtonStyle.swift
  Source/UI/PaymentForm/Default Implementation/BillingFormSummary/Summary/Button/DefaultEditBillingDetailsButtonStyle.swift
  Source/UI/PaymentForm/Default Implementation/BillingFormSummary/Summary/View/DefaultBillingSummaryViewStyle.swift
  Source/UI/PaymentForm/Default Implementation/Cardholder/DefaultCardholderFormStyle.swift
  Source/UI/PaymentForm/Default Implementation/DefaultPayButtonFormStyle.swift
  Source/UI/PaymentForm/Default Implementation/DefaultPaymentFormStyle.swift
  Source/UI/PaymentForm/ViewController/PaymentViewController.swift
  Tests/UI/BillingForm/View/BillingFormButtonViewTests.swift
  Tests/UI/FramesUIStyle/FramesUIStyleColorTests.swift
  Tests/UI/FramesUIStyle/FramesUIStyleFontTests.swift
  iOS Example Frame Carthage/iOS Example Frame Carthage.xcodeproj/project.pbxproj
Labels: Enhancement

#305 PIMOB-1234: Support Spanish Language for frames
  Source/Resources/es.lproj/Localizable.strings
  iOS Example Frame/iOS Example FrameUITests/FrameUITests.swift
Labels: Feature

#310 PIMOB-1441: Billing Nav Controller Buttons Font
  Source/UI/BillingForm/ViewController/BillingFormViewController.swift
Labels: Upgrade

#312 PIMOB-1434: Fix Maestro card number formatting
  Checkout/Checkout/Source/Model/Card+Scheme.swift
  Checkout/Checkout/Test/Validation/CardNumberValidatorTests.swift
Labels: Fix
