Repository checkout/frames-ios, pull requests merged in 2022-08, with the labels that each got.

#230 PIMOB-1266: Update header view on scroll
  Source/Core/Constants/Constants+Padding.swift
  Source/Extensions/UIViewControllerExtensions.swift
  Source/UI/Controllers/CardViewController.swift
  Source/UI/Controllers/CountrySelectionViewController.swift
  Source/UI/NewUI/PaymentForm/Default Implementation/DefaultPaymentFormStyle.swift
  Source/UI/NewUI/PaymentForm/Default Implementation/DefaultPaymentHeaderCellStyle.swift
  Source/UI/NewUI/PaymentForm/StyleProtocol/PaymentFormStyle.swift
  Source/UI/NewUI/PaymentForm/StyleProtocol/PaymentHeaderCellStyle.swift
  Source/UI/NewUI/PaymentForm/View/PaymentHeaderView.swift
  Source/UI/NewUI/PaymentForm/ViewController/PaymentViewController.swift
  iOS Example Frame/iOS Example Frame/CustomStyle1.swift
  iOS Example Frame/iOS Example Frame/CustomStyle2.swift
Labels: Fix

#231 PIMOB-1337: Fix error border line for payment UI components
  Source/UI/NewUI/CommonUI/View/Component/InputView.swift
Labels: Fix

#235 PIMOB-XXXX: Update README
  README.md
Labels: Enhancement

#234 PIMOB-1359: Visa card should allow 19-digit length
  Checkout/Checkout/Source/Model/Card+Scheme.swift
  Checkout/Checkout/Test/Validation/CardNumberValidatorTests.swift
  Source/Core/Constants/Constants+Padding.swift
  Source/UI/NewUI/PaymentForm/View/SecurityCodeViewModel.swift
  Tests/Core/CardUtilsTests.swift
  iOS Example Frame/iOS Example Frame/CustomStyle1.swift
Labels: Fix

#239 PIMOB-1366: Enable maestro to validate without cvv
  Checkout/Checkout/Source/Model/Card+Scheme.swift
  Checkout/Checkout/Test/Model/CardSchemeTests.swift
  Checkout/Checkout/Test/Validation/CVVValidatorTests.swift
Labels: Fix

#238 PIMOB-1332: Add Matrix theming
  Source/UI/NewUI/BillingForm/Default Implementation/Elements/Error/DefaultErrorInputLabelStyle.swift
  Source/UI/NewUI/CommonUI/Protocols/Elements/ElementErrorViewStyle.swift
  Source/UI/NewUI/CommonUI/View/Core/ButtonView.swift
  Source/UI/NewUI/PaymentForm/StyleProtocol/PaymentFormStyle.swift
  Tests/UI/New UI/BillingForm/View/BillingFormButtonViewTests.swift
  Tests/UI/New UI/BillingForm/View/BillingFormSummaryViewTests.swift
  iOS Example Frame Carthage/iOS Example Frame Carthage.xcodeproj/project.pbxproj
  iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.pbxproj
  iOS Example Frame/iOS Example Frame.xcodeproj/project.pbxproj
  iOS Example Frame/iOS Example Frame/AppDelegate.swift
  iOS Example Frame/iOS Example Frame/Assets.xcassets/arrow_green_down.imageset/Contents.json
  iOS Example Frame/iOS Example Frame/Assets.xcassets/arrow_green_down.imageset/arrow_green_down.pdf
  iOS Example Frame/iOS Example Frame/CustomStyle1.swift
  iOS Example Frame/iOS Example Frame/CustomStyle2.swift
  iOS Example Frame/iOS Example Frame/Info.plist
  iOS Example Frame/iOS Example Frame/MainViewController.swift
  iOS Example Frame/iOS Example Frame/UIFont+Extensions.swift
  iOS Example/iOS Example/SF-Mono/SF-Mono-Bold.otf
  iOS Example/iOS Example/SF-Mono/SF-Mono-BoldItalic.otf
  iOS Example/iOS Example/SF-Mono/SF-Mono-Heavy.otf
  iOS Example/iOS Example/SF-Mono/SF-Mono-HeavyItalic.otf
  iOS Example/iOS Example/SF-Mono/SF-Mono-Light.otf
  iOS Example/iOS Example/SF-Mono/SF-Mono-LightItalic.otf
  iOS Example/iOS Example/SF-Mono/SF-Mono-Medium.otf
  iOS Example/iOS Example/SF-Mono/SF-Mono-MediumItalic.otf
  iOS Example/iOS Example/SF-Mono/SF-Mono-Regular.otf
  iOS Example/iOS Example/SF-Mono/SF-Mono-RegularItalic.otf
  iOS Example/iOS Example/SF-Mono/SF-Mono-Semibold.otf
  iOS Example/iOS Example/SF-Mono/SF-Mono-SemiboldItalic.otf
Labels: Enhancement

#240 PIMOB-1374: Minor UI changes
  Source/Extensions/UIViewControllerExtensions.swift
  Source/UI/Controllers/CardViewController.swift
  Source/UI/Controllers/CountrySelectionViewController.swift
  Source/UI/NewUI/PaymentForm/View/PaymentHeaderView.swift
  Source/UI/NewUI/PaymentForm/ViewController/PaymentViewController.swift
Labels: Fix

#236 PIMOB-1365: Integrate supported card scheme list with all UI components
  Source/Extensions/UIViewExtensions.swift
  Source/UI/NewUI/PaymentForm/Default Implementation/DefaultPaymentHeaderCellStyle.swift
  Source/UI/NewUI/PaymentForm/StyleProtocol/PaymentHeaderCellStyle.swift
  Source/UI/NewUI/PaymentForm/View/CardNumber/CardNumberViewModel.swift
  Source/UI/NewUI/PaymentForm/View/PaymentHeaderView.swift
  Source/UI/NewUI/PaymentForm/ViewController/PaymentViewController.swift
  Source/UI/NewUI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift
  Tests/UI/New UI/BillingForm/ViewController/PaymentViewControllerTests.swift
  Tests/UI/New UI/BillingForm/ViewModel/PaymentViewModelTests.swift
  Tests/UI/New UI/PaymentForm/CardNumber/CardNumberViewModelTests.swift
  Tests/UI/UIViewExtensionTests.swift
  iOS Example Frame Carthage/iOS Example Frame Carthage.xcodeproj/project.pbxproj
  iOS Example Frame/iOS Example Frame/CustomStyle1.swift
  iOS Example Frame/iOS Example Frame/CustomStyle2.swift
  iOS Example Frame/iOS Example Frame/MainViewController.swift
Labels: Fix

#241 PIMBOB-1265: Create Card token using sample app with new UI
  Source/Core/CheckoutAPIService.swift
  Source/Core/Constants/Constants+LocalizationKeys.swift
  Source/Core/Constants/Constants+Style.swift
  Source/Extensions/UIStackViewExtension.swift
  Source/Resources/en.lproj/Localizable.strings
  Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Header/Cancel/DefaultCancelButtonFormStyle.swift
  Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Header/Done/DefaultDoneFormButtonStyle.swift
  Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Header/Title/DefaultHeaderLabelFormStyle.swift
  Source/UI/NewUI/BillingForm/Default Implementation/Elements/Country/DefaultCountryFormButtonStyle.swift
  Source/UI/NewUI/BillingForm/Default Implementation/Elements/Error/DefaultErrorInputLabelStyle.swift
  Source/UI/NewUI/BillingForm/Default Implementation/Elements/Hint/DefaultHintInputLabelStyle.swift
  Source/UI/NewUI/BillingForm/Default Implementation/Elements/TextField/DefaultTextField.swift
  Source/UI/NewUI/BillingForm/Default Implementation/Elements/Title/DefaultTitleLabelStyle.swift
  Source/UI/NewUI/CommonUI/Protocols/Elements/ElementStyle.swift
  Source/UI/NewUI/CommonUI/View/Component/SimpleErrorView.swift
  Source/UI/NewUI/CommonUI/View/Core/ButtonView.swift
  Source/UI/NewUI/CommonUI/View/Core/LabelView.swift
  Source/UI/NewUI/PaymentForm/Default Implementation/BillingFormSummary/Summary/Button/DefaultAddBillingDetailsButtonStyle.swift
  Source/UI/NewUI/PaymentForm/Default Implementation/BillingFormSummary/Summary/Button/DefaultEditBillingDetailsButtonStyle.swift
  Source/UI/NewUI/PaymentForm/Default Implementation/DefaultPayButtonFormStyle.swift
  Source/UI/NewUI/PaymentForm/Default Implementation/DefaultPaymentFormStyle.swift
  Source/UI/NewUI/PaymentForm/Factory/PaymentFormFactory.swift
  Source/UI/NewUI/PaymentForm/StyleProtocol/PaymentFormStyle.swift
  Source/UI/NewUI/PaymentForm/View/BillingFormSummaryView.swift
  Source/UI/NewUI/PaymentForm/View/CardNumber/CardNumberView.swift
  Source/UI/NewUI/PaymentForm/View/CardNumber/CardNumberViewModel.swift
  Source/UI/NewUI/PaymentForm/View/ExpiryDateView.swift
  Source/UI/NewUI/PaymentForm/View/PaymentHeaderView.swift
  Source/UI/NewUI/PaymentForm/View/SecurityCodeView.swift
  Source/UI/NewUI/PaymentForm/ViewController/PaymentViewController.swift
  Source/UI/NewUI/PaymentForm/ViewModel/CardCreationModel.swift
  Source/UI/NewUI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift
  Source/UI/NewUI/PaymentForm/ViewModel/PaymentViewModel.swift
  Tests/Mocks/MockCardNumberViewModelDelegate.swift
  Tests/Mocks/PaymentViewControllerMockDelegate.swift
  Tests/Mocks/StubCheckoutAPIService.swift
  Tests/UI/New UI/BillingForm/View/BillingFormButtonViewTests.swift
  Tests/UI/New UI/BillingForm/View/BillingFormSummaryViewTests.swift
  Tests/UI/New UI/BillingForm/ViewController/PaymentViewControllerTests.swift
  Tests/UI/New UI/BillingForm/ViewModel/PaymentViewModelTests.swift
  Tests/UI/New UI/PaymentForm/CardNumber/CardNumberViewModelTests.swift
  Tests/UI/New UI/PaymentForm/PaymentViewControllerTests.swift
  Tests/UI/New UI/PaymentFormFactoryTests.swift
  Tests/UI/UIStackViewExtensionTests.swift
  iOS Example Frame Carthage/iOS Example Frame Carthage.xcodeproj/project.pbxproj
  iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.pbxproj
  iOS Example Frame/iOS Example Frame/CustomStyle1.swift
  iOS Example Frame/iOS Example Frame/CustomStyle2.swift
  iOS Example Frame/iOS Example Frame/MainViewController.swift
Labels: Feature

#248 PIMOB-1365: Not allow any merchant to pass `unknown` card scheme
  Source/Core/Models/CardScheme.swift
  Tests/Core/CardSchemeTests.swift
Labels: Fix

#249 PIMOB-1366: Fix accepting maestro cards
  Source/UI/NewUI/PaymentForm/View/CardNumber/CardNumberViewModel.swift
  Tests/UI/New UI/PaymentForm/CardNumber/CardNumberViewModelTests.swift
Labels: Fix

#245 PIMOB-1377: Try to improve user experience customising UI
  Source/Core/Logging/Theme.swift
  Source/UI/BillingForm/Default Implementation/Elements/TextField/DefaultTextField.swift
  Source/UI/BillingForm/View/BillingFormTextFieldView.swift
  Source/UI/CommonUI/Protocols/Elements/ElementTextFieldStyle.swift
  Source/UI/CommonUI/View/Core/TextFieldView.swift
  Source/UI/PaymentForm/Default Implementation/CardNumber/DefaultCardNumberFormStyle.swift
  Source/UI/PaymentForm/Default Implementation/ExpiryDate/DefaultExpiryDateFormStyle.swift
  Source/UI/Theme/BillingForm/Theme+BillingCountryInput.swift
  Source/UI/Theme/BillingForm/Theme+BillingForm.swift
  Source/UI/Theme/BillingForm/Theme+BillingHeader.swift
  Source/UI/Theme/BillingForm/Theme+BillingInput.swift
  Source/UI/Theme/Generic/Theme+Button.swift
  Source/UI/Theme/Generic/Theme+Error.swift
  Source/UI/Theme/Generic/Theme+Mandatory.swift
  Source/UI/Theme/Generic/Theme+PageHeaderTitle.swift
  Source/UI/Theme/Generic/Theme+Subtitle.swift
  Source/UI/Theme/Generic/Theme+TextField.swift
  Source/UI/Theme/Generic/Theme+Title.swift
  Source/UI/Theme/PaymentForm/Theme+AddBillingSectionButton.swift
  Source/UI/Theme/PaymentForm/Theme+BillingSummary.swift
  Source/UI/Theme/PaymentForm/Theme+CardNumberSection.swift
  Source/UI/Theme/PaymentForm/Theme+PayButton.swift
  Source/UI/Theme/PaymentForm/Theme+PaymentFormStyle.swift
  Source/UI/Theme/PaymentForm/Theme+PaymentHeader.swift
  Source/UI/Theme/PaymentForm/Theme+PaymentHeaderSubtitle.swift
  Source/UI/Theme/Theme.swift
  Tests/UI/BillingForm/View/TextFieldViewTests.swift
  iOS Example Frame Carthage/iOS Example Frame Carthage.xcodeproj/project.pbxproj
  iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.pbxproj
  iOS Example Frame/iOS Example Frame.xcodeproj/project.pbxproj
  iOS Example Frame/iOS Example Frame/Factory/Factory.swift
  iOS Example Frame/iOS Example Frame/Style/CustomStyle1.swift
  iOS Example Frame/iOS Example Frame/Style/CustomStyle2.swift
  iOS Example Frame/iOS Example Frame/Style/Style.swift
  iOS Example Frame/iOS Example Frame/ThemeDemo.swift
Labels: Feature

#252 PIMOB-XXXX: Fix swift lint for M1
  iOS Example Frame Carthage/iOS Example Frame Carthage.xcodeproj/project.pbxproj
  iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.pbxproj
  iOS Example Frame/iOS Example Frame.xcodeproj/project.pbxproj
Labels: Fix

#254 PIMOB-1381: Enable control over components required for payment input validation
  Source/UI/PaymentForm/Default Implementation/DefaultPaymentFormStyle.swift
  Source/UI/PaymentForm/StyleProtocol/PaymentFormStyle.swift
  Source/UI/PaymentForm/ViewController/PaymentViewController.swift
  Source/UI/PaymentForm/ViewModel/CardCreationModel.swift
  Source/UI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift
  Source/UI/Theme/PaymentForm/Theme+PaymentFormStyle.swift
  Tests/UI/BillingForm/ViewModel/PaymentViewModelTests.swift
  iOS Example Frame/iOS Example Frame/Style/CustomStyle1.swift
Labels: Feature

#256 PIMOB-1395: Fix add billing form when click on the chevron
  Source/UI/CommonUI/View/Component/SelectionButtonView.swift
Labels: Fix

#257 PIMOB-1370: Fix Input UI components spaces
  Source/UI/CommonUI/View/Component/InputView.swift
Labels: Fix

#258 PIMOB-1395: Fix summary button click
  Source/UI/PaymentForm/View/BillingFormSummaryView.swift
Labels: Fix

#263 PIMOB-1376: Fix input behaviour
  Source/UI/CommonUI/View/Core/SecureDisplayView.swift
  Source/UI/CommonUI/View/Core/TextFieldView.swift
  Tests/UI/BillingForm/View/SecureDisplayViewTests.swift
  bitrise.yml
Labels: Fix

#265 PIMOB-1417: Update text content
  Source/Resources/en.lproj/Localizable.strings
  iOS Example Frame/iOS Example Frame/Style/CustomStyle1.swift
Labels: Enhancement
